package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/sirrobot01/archbench/spec"
)

func newGenerateCmd() *cobra.Command {
	var (
		specPath string
		outPath  string
		force    bool
	)
	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate a GitHub Actions workflow that runs the suite's github-actions targets",
		RunE: func(cmd *cobra.Command, _ []string) error {
			s, err := spec.LoadSpec(specPath)
			if err != nil {
				return err
			}

			workflow, err := generateWorkflow(s, specPath)
			if err != nil {
				return err
			}

			if _, err := os.Stat(outPath); err == nil && !force {
				return fmt.Errorf("%s already exists (use --force to overwrite)", outPath)
			}
			if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(outPath, []byte(workflow), 0o644); err != nil {
				return err
			}
			cmd.Printf("wrote %s\n", outPath)
			return nil
		},
	}
	cmd.Flags().StringVarP(&specPath, "spec", "s", spec.DefaultSpecFile, "path to spec file")
	cmd.Flags().StringVarP(&outPath, "out", "o", filepath.Join(".github", "workflows", "archbench.yml"), "path for the generated workflow")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing workflow")
	return cmd
}

// generateWorkflow renders a GitHub Actions workflow that runs each
// github-actions target as a matrix job on its configured runner.
func generateWorkflow(s *spec.Spec, specPath string) (string, error) {
	var jobs []spec.Target
	for _, t := range s.Targets {
		if t.Type == spec.TargetGitHubActions {
			jobs = append(jobs, t)
		}
	}
	if len(jobs) == 0 {
		return "", fmt.Errorf("spec has no github-actions targets; add a target with `type: github-actions`")
	}

	var b strings.Builder
	b.WriteString("# Generated by `archbench generate`. Edit the spec and re-run to update.\n")
	fmt.Fprintf(&b, "name: %s\n\n", s.Name)
	b.WriteString("on:\n")
	b.WriteString("  push:\n")
	b.WriteString("    branches: [main]\n")
	b.WriteString("  pull_request:\n")
	b.WriteString("  workflow_dispatch:\n\n")
	b.WriteString("jobs:\n")
	b.WriteString("  archbench:\n")
	b.WriteString("    name: ${{ matrix.target }}\n")
	b.WriteString("    runs-on: ${{ matrix.runs-on }}\n")
	b.WriteString("    strategy:\n")
	b.WriteString("      fail-fast: false\n")
	b.WriteString("      matrix:\n")
	b.WriteString("        include:\n")
	for _, t := range jobs {
		runsOn := t.RunsOn
		if runsOn == "" {
			runsOn = "ubuntu-latest"
		}
		fmt.Fprintf(&b, "          - target: %s\n", t.Name)
		fmt.Fprintf(&b, "            runs-on: %s\n", runsOn)
	}
	b.WriteString("    steps:\n")
	b.WriteString("      - uses: actions/checkout@v6\n")
	if s.Parser == "go-test" {
		b.WriteString("      - uses: actions/setup-go@v6\n")
		b.WriteString("        with:\n")
		b.WriteString("          go-version: stable\n")
	}
	b.WriteString("      - name: Install archbench\n")
	b.WriteString("        run: go install github.com/sirrobot01/archbench@latest\n")
	b.WriteString("      - name: Run archbench\n")
	fmt.Fprintf(&b, "        run: archbench run --spec %s --target ${{ matrix.target }}\n", specPath)
	b.WriteString("      - uses: actions/upload-artifact@v5\n")
	b.WriteString("        with:\n")
	b.WriteString("          name: archbench-${{ matrix.target }}\n")
	b.WriteString("          path: archbench-results/${{ matrix.target }}.json\n")
	return b.String(), nil
}
